let mapleader="\\"

" Automatically install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync
endif

" https://vimawesome.com/
" Set up Plugins
call plug#begin('~/.vim/bundle')
Plug 'junegunn/vim-plug'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'arcticicestudio/nord-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'PotatoesMaster/i3-vim-syntax'
Plug 'terryma/vim-multiple-cursors'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tweekmonster/braceless.vim'
call plug#end()

runtime! archlinux.vim

" Basic Settings
set nocompatible
syntax on
filetype plugin indent on
set path+=**
set number relativenumber
set laststatus=2
set showcmd
set clipboard=unnamed
set encoding=utf-8
set backspace=indent,eol,start
set splitbelow splitright
set ruler
set wildmenu
set wildmode=longest,list,full
set viminfo=%,<800,'10,/50,:100,h,f0,n~/.vim/viminfo

set switchbuf=usetab,newtab
set backup
"set backupext=.bak
set confirm
set hlsearch
set incsearch
set showmatch
set ignorecase
set smartcase

set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
"set softtabstop=4
"set expandtab

set display+=lastline
set list
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+,eol:$,space:.
"set showmode
set showbreak=+++\
set showtabline=2
set t_Co=256

"let g:airline_theme='deus' "for dracula theme
let g:airline_theme='base16' "for nord theme
let g:airline_powerline_fonts = 1

"let g:dracula_italic = 0
"let g:dracula_colorterm = 0
"colorscheme dracula
colorscheme nord

let g:limelight_conceal_ctermcfg = 'gray'
let g:limelight_conceal_guifg = 'DarkGray'

" Remap capslock to escape within Vim. If not already systemwide
" au VimEnter * silent! !xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
" au VimLeave * silent! !xmodmap -e 'clear Lock' -e 'keycode 0x42 = Caps_Lock'

" Change and set mappings
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

map <leader>q :q<CR>
map <leader>w :w<CR>
map <leader>f :Goyo<CR>
map <leader>l :Limelight!!<CR>
map <leader>n :NERDTree<CR>

map <F7> :setlocal spell! spelllang=en_us<CR>
" Automatically deletes all trailing whitespace on save.
autocmd BufWritePre * %s/\s\+$//e
" Automatically reload Xresouces on save
autocmd BufWritePost *Xresources,*Xdefaults silent! !xrdb %

" Navigating with guides
    inoremap <leader><leader> <Esc>/<Enter>"_c4l
    vnoremap <leader><leader> <Esc>/<Enter>"_c4l
    map <leader><leader> <Esc>/<Enter>"_c4l

" if mouse needs to be enabled
"if has('mouse')
"    set mouse=a
"endif

" vim:set ft=vim et sw=2:
