
" set leader key to backslash explicitly
let mapleader="\\"

" Automatically install vim-plug
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync
endif

" https://vimawesome.com/
" Set up Plugins
call plug#begin('~/.vim/bundle')
Plug 'junegunn/vim-plug'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'junegunn/fzf.vim'
Plug 'dracula/vim', { 'as': 'dracula' }
Plug 'arcticicestudio/nord-vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'PotatoesMaster/i3-vim-syntax'
Plug 'w0rp/ale'
Plug 'scrooloose/nerdtree'
Plug 'scrooloose/nerdcommenter'
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-surround'
call plug#end()

runtime! archlinux.vim

" Basic Settings
set nocompatible
syntax on
filetype plugin indent on

set encoding=utf-8

set path+=**
set number relativenumber
set laststatus=2
set showtabline=2
set ruler
set wildmenu
set wildmode=longest,list,full
set showcmd
" set showmode

set clipboard=unnamed
set backspace=indent,eol,start
set splitbelow splitright
set viminfo=%,<800,'10,/50,:100,h,f0,n~/.vim/viminfo
set switchbuf=usetab,newtab

set backup
set confirm

set hlsearch
set incsearch
set showmatch
set ignorecase
set smartcase

set foldcolumn=2
set foldenable
set foldmethod=manual

set autoindent
set smartindent
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab

set display+=lastline
set list
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+,eol:$,space:.
set showbreak=+++\

set t_Co=256

" Theme Settings
"let g:airline_theme='deus' "for dracula theme
"let g:airline_theme='bubblegum' "for nord theme
let g:airline_theme='base16' "for nord theme
let g:airline_powerline_fonts = 1

"colorscheme dracula
"let g:dracula_italic = 0
"let g:dracula_colorterm = 0
colorscheme nord
let g:nord_comment_brightness = 15

" Plugin/Tool Settings
let g:limelight_conceal_ctermcfg = 'gray'
let g:limelight_conceal_guifg = 'DarkGray'

" Key Mapping/Settings
" Remap capslock to escape within Vim. If not already systemwide
" au VimEnter * silent! !xmodmap -e 'clear Lock' -e 'keycode 0x42 = Escape'
" au VimLeave * silent! !xmodmap -e 'clear Lock' -e 'keycode 0x42 = Caps_Lock'

map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" normal mode mappings for tools
nnoremap <leader>q :q<CR>
nnoremap <leader>w :w<CR>
nnoremap <leader>f :Goyo<CR>
nnoremap <leader>l :Limelight!!<CR>
nnoremap <leader>n :NERDTree<CR>
nnoremap <leader>t :term ++close<CR>
nnoremap <leader>] :!ctags -R<CR><CR>

nnoremap <F7> :setlocal spell! spelllang=en_us<CR>
nnoremap <F2> :term ++close<CR>

" AutoCmd Settings
" Automatically deletes all trailing whitespace on save.
autocmd BufWritePre * %s/\s\+$//e
" Automatically reload Xresouces on save
autocmd BufWritePost *Xresources,*Xdefaults silent! !xrdb %

" Navigation/Mouse Settings
" if mouse needs to be enabled
"if has('mouse')
"    set mouse=a
"endif

" Modeline
" vim: set ft=vim sw=2 et:
